include:
- ./src/function-execute.js
kind: ArchiveUploadSpec
name: src-function-execute-js-Gn41

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: execute-cbe5b8d1-5440-4b90-b025-2d752d6a6adc
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://src-function-execute-js-Gn41
  environment:
    name: nodejs
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-05-30T23:10:28Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: execute
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: nodejs
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: execute-cbe5b8d1-5440-4b90-b025-2d752d6a6adc
      namespace: default
  requestsPerPod: 1
  resources: {}
