apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: run-isolated
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: run-js
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /run-isolated
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /run-isolated
