apiVersion: v1
kind: Service
metadata:
  name: router-load-balancer
  namespace: fission
spec:
  selector:
    svc: router
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30035
  clusterIP: 10.106.45.54
  clusterIPs:
    - 10.106.45.54
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127